server:
  port: 8085

spring:
  application:
    name: resenias
  datasource:
    url: jdbc:postgresql://localhost:5434/b2bmatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: b2bmatch_resenias
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${JWT_SECRET}

notifications:
  api-url: ${NOTIFICACIONES_API_URL:http://notificaciones:8086}

internal:
  service-key: ${INTERNAL_SERVICE_KEY}